baseURL = "https://myrecipe.runoshun.net/"
languageCode = "ja-jp"
title = "マイレシピノート"
theme = "landing-page-hugo"
hasCJKLanguage = true

[permalinks]
  posts = "/:year/:month/:title/"

[params]
  description = "レシピ記録・買い物メモアプリ"
	googleAnalytics = "UA-124834346-1"

[[params.social]]
	title = "iPhone"
	icon = "apple"
	url = "https://itunes.apple.com/us/app/%E3%83%9E%E3%82%A4%E3%83%AC%E3%82%B7%E3%83%94%E3%83%8E%E3%83%BC%E3%83%88/id1434139059?l=ja&ls=1&ct=supportPage&mt=8"